import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import me from "public/me.png";
import aboutMe from "public/about-me.gif";
import work1 from "public/1.webp";
import work2 from "public/2.webp";
import work3 from "public/3.webp";
import work4 from "public/4.webp";
import work5 from "public/5.webp";
import work6 from "public/6.webp";
import styles from "@/styles/Home.module.css";
import { FiSend } from 'react-icons/fi';
import { GrAppsRounded } from 'react-icons/gr';
import { FiAward } from 'react-icons/fi';
import { BiSupport } from 'react-icons/bi';
import { BsFillMoonStarsFill, BsWhatsapp } from 'react-icons/bs';
import { DiCss3 } from 'react-icons/di';
import { FaReact, FaBootstrap } from 'react-icons/fa';
import { SiTailwindcss, SiJavascript } from 'react-icons/si';
import { AiOutlineInstagram, AiOutlineGithub, AiFillFacebook, AiOutlineHome, AiOutlineUser, AiOutlineLaptop, AiOutlineSend, AiOutlineHtml5, AiOutlineFileDone, AiOutlineArrowUp, AiOutlineMail, AiOutlineArrowRight } from "react-icons/ai";
import { useState } from "react";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [navApps, setNavApps] = useState(false);
    const [darkMode, setDarkMode] = useState(false);
    const [scroll, setScroll] = useState(false);

    const linkRefSatu = useRef(null);
    const linkRefDua = useRef(null);
    const linkRefTiga = useRef(null);
    const linkRefEmpat = useRef(null);

    const goTo = (ref) => {
        window.scrollTo({
            top: ref.offsetTop,
            left: 0,
            behavior: "smooth",
        });
    };

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Rrrrrrr.</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <main className="bg-white lg:px-8">
                <div className="bg-white pt-4 px-4 dark:bg-slate-900">
                    <section className="text-slate-800 lg:mb-5">
                        <div className="text-slate-800 lg:flex lg:items-center lg:justify-between ">
                            <div className="flex justify-between">
                                <h1 className="font-superMario text-2xl  "><a href="#">Rrrrrrr <span className=" -ml-1 bg-gradient-to-r from-emerald-400 to-sky-400 bg-clip-text text-transparent"> Dev.</span></a></h1>
                                <GrAppsRounded className="text-3xl cursor-pointer lg:hidden" onClick={() => setNavApps(!navApps)} />
                            </div>
                            <hr className="bg-slate-800 h-[2px] mt-2 opacity-50 shadow-md" />
                            <nav className={!navApps ? "opacity-0 transition-all ease-in duration-300 lg:opacity-100 lg:flex lg:justify-end" : " bg-slate-200 px-2 py-2 rounded-md opacity-100 transition-all ease-in duration-300 my-4 cursor-pointer"}>
                                <ul className="flex justify-between items-center lg:cursor-pointer">
                                    <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200" onClick={() => goTo(linkRefSatu.current)}>
                                        <AiOutlineHome className="text-2xl lg:hidden" />
                                        <span>Home</span>
                                    </li>
                                    <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200" onClick={() => goTo(linkRefDua.current)}>
                                        <AiOutlineUser className="text-2xl lg:hidden" />
                                        <span >About</span>
                                    </li>
                                    <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200" onClick={() => goTo(linkRefTiga.current)}>
                                        <AiOutlineLaptop className="text-2xl lg:hidden" />
                                        <span >Works</span>
                                    </li>
                                    <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200" onClick={() => goTo(linkRefEmpat.current)}>
                                        <AiOutlineSend className="text-2xl lg:hidden" />
                                        <span >Contact</span>
                                    </li>
                                    <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200 relative" onClick={() => setDarkMode(!darkMode)}>
                                        <BsFillMoonStarsFill className="text-2xl" />
                                        <span className="lg:hidden">Theme</span>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </section>
                    <div className="lg:flex flex-row gap-7 justify-between mb-9 lg:mt-20">
                        <section className="flex items-center mb-5" ref={linkRefSatu}>
                            <div className="flex flex-col items-center gap-3 ml-[30px]">
                                <a href="https://www.instagram.com/rfkyyyyy/">
                                    <AiOutlineInstagram className="bg-gradient-to-tr from-yellow-400 to-purple-500 text-slate-100 text-3xl rounded-lg animate-bounce hover:animate-none hover:scale-110 transition-all duration-500" />
                                </a>
                                <span className="w-full bg-slate-800 h-[2px] border"></span>
                                <a href="https://github.com/ZoyaaaZoy">
                                    <AiOutlineGithub className="text-black text-3xl animate-bounce hover:animate-none hover:scale-110 transition-all duration-500" />
                                </a>
                                <span className="w-full bg-slate-800 h-[2px] border"></span>
                                <a href="https://web.facebook.com/rifkyandriansyah.anggela">
                                    <AiFillFacebook className="text-blue-600 text-3xl animate-bounce hover:animate-none hover:scale-110 transition-all duration-500" />
                                </a>
                            </div>
                            <div className=" lg:ml-5 relative mr-auto overflow-hidden bg-gradient-to-r from-emerald-500 to-sky-400 rounded-r-full w-60 h-60 mx-auto md:h-96 md:w-96">
                                <Image src={me} objectFit="cover" />
                            </div>
                        </section>
                        <div className="text-slate-700 pb-8 mt-3 lg:flex lg:flex-col lg:justify-center lg:items-center">
                            <h1 className="text-4xl font-bold font-nulshock">Rifky Andriansyah</h1>
                            <h3 className="flex items-center font-semibold text-lg">
                                <span className="w-24 bg-slate-800 h-1 border mr-5 ml-1"></span> FrontEnd
                                Developer.
                            </h3>
                            <p className="text-slate-500 text-md font-[poppins] mb-3">
                                I'am FrontEnd Developer based in <span className="text-black font-serif font-semibold">Bandung</span> and i'am very
                                passionate and dedicated to my work.
                            </p>
                            <button className=" px-4 py-3 bg-slate-800 flex items-center text-white font-semibold rounded-[10px] font-[poppins]">Say Hello<FiSend className="ml-2 mt-[3px]" /></button>
                        </div>
                    </div>
                </div>
                <hr className="h-1 bg-slate-200" />
                <div className="pt-5 bg-white px-3" ref={linkRefDua}>
                    <div>
                        <h1 className="text-slate-700 text-3xl text-center font-semibold">About Me</h1>
                        <h4 className="text-center text-slate-700">My Intoduction</h4>
                    </div>
                    <div className="overflow-hidden relative rounded-md w-60 h-60 mx-auto mb-4 md:h-96 md:w-96">
                        <Image src={aboutMe} objectFit="cover" />
                    </div>
                    <div className="flex justify-evenly items-center">
                        <div className="bg-slate-800 flex flex-col justify-center items-center p-4 rounded-lg">
                            <FiAward className="text-slate-100 text-3xl" />
                            <h1 className="text-lg font-semibold">Experience</h1>
                            <p>1 Years</p>
                        </div>
                        <div className="bg-slate-800 flex flex-col justify-center items-center p-4 rounded-lg">
                            <AiOutlineFileDone className="text-slate-100 text-3xl" />
                            <h1 className="text-lg font-semibold">Completed</h1>
                            <p>5+ Project</p>
                        </div>
                        <div className="bg-slate-800 flex flex-col justify-center items-center p-4 rounded-lg">
                            <BiSupport className="text-slate-100 text-3xl" />
                            <h1 className="text-lg font-semibold">Support</h1>
                            <p>Online 24/7</p>
                        </div>

                    </div>
                    <h1 className="text-slate-700 font-semibold text-center mt-5 text-xl">What I Use?</h1>
                    <div className="py-2 flex gap-3 justify-evenly">
                        <div className="flex flex-col gap-2 justify-start py-2">
                            <h1 className="text-slate-700">Programming language</h1>
                            <div className="bg-slate-800 p-4 flex flex-col items-center gap-1 rounded-lg">
                                <h1 className="font-semibold">HTML</h1>
                                <AiOutlineHtml5 className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center gap-1 rounded-lg">
                                <h1 className="font-semibold">CSS</h1>
                                <DiCss3 className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center gap-1 rounded-lg">
                                <h1 className="font-semibold">JAVASCRIPT</h1>
                                <SiJavascript className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                        </div>
                        <div className="flex flex-col gap-2 justify-start py-2">
                            <h1 className="text-slate-700">Library & Framework</h1>
                            <div className="bg-slate-800 p-4 flex flex-col items-center gap-1 rounded-lg">
                                <h1 className="font-semibold">REACT</h1>
                                <FaReact className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center gap-1 rounded-lg">
                                <h1 className="font-semibold">TAILWIND</h1>
                                <SiTailwindcss className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center gap-1 rounded-lg">
                                <h1 className="font-semibold">BOOTSTRAP</h1>
                                <FaBootstrap className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr className="h-1 bg-slate-200" />
                <div className="px-4 bg-white pt-4" ref={linkRefTiga}>
                    <div className="bg-white">
                        <h1 className="text-slate-700 text-3xl text-center font-semibold">My Works</h1>
                        <h4 className="text-center text-slate-700">My Creation</h4>
                    </div>
                    <div className=" bg-white grid grid-cols-2 p-3 gap-2">
                        <div className=" bg-slate-700 aspect-video hover:scale-110 transition-all duration-500"><Image src={work1} /></div>
                        <div className=" bg-slate-700 aspect-video hover:scale-110 transition-all duration-500"><Image src={work2} /></div>
                        <div className=" bg-slate-700 aspect-video hover:scale-110 transition-all duration-500"><Image src={work3} /></div>
                        <div className=" bg-slate-700 aspect-video hover:scale-110 transition-all duration-500"><Image src={work4} /></div>
                        <div className=" bg-slate-700 aspect-video hover:scale-110 transition-all duration-500"><Image src={work5} /></div>
                        <div className=" bg-slate-700 aspect-video hover:scale-110 transition-all duration-500"><Image src={work6} /></div>
                    </div>
                </div>
                <hr className="h-1 bg-slate-200" />
                <div className="px-4 bg-white pt-4" ref={linkRefEmpat}>
                    <div>
                        <h1 className="text-slate-700 text-3xl text-center font-semibold">Contact Me</h1>
                        <h4 className="text-center text-slate-700">Send Your Message!</h4>
                    </div>
                    <div>
                        <div className="flex flex-col gap-2">
                            <h1 className="text-slate-700 text-center">Talk To Me!</h1>
                            <div className="bg-slate-800 flex flex-col gap-2 justify-center items-center rounded-[15px] px-3 py-5">
                                <AiOutlineMail className="text-4xl" />
                                <h1 className="font-semibold">Email</h1>
                                <h3>rifkyandriansyah444@gmail.com</h3>
                                <span className="flex items-center hover:translate-x-2 cursor-pointer transition-all duration-500 text-emerald-500  ">Write Me <AiOutlineArrowRight className="mt-1 ml-2" /></span>
                            </div>

                            <div className="bg-slate-800 flex flex-col gap-2 justify-center items-center rounded-[15px] px-3 py-5">
                                <BsWhatsapp className="text-4xl" />
                                <h1 className="font-semibold">Whatsapp</h1>
                                <h3>081222393543</h3>
                                <span className="flex items-center hover:translate-x-2 cursor-pointer transition-all duration-500 text-emerald-500  ">Write Me <AiOutlineArrowRight className="mt-1 ml-2" /></span>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <footer>ini footer</footer>
        </div>
    );
}
