import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import me from "public/me.png";
import aboutMe from "public/about-me.gif";
import styles from "@/styles/Home.module.css";
import { FiSend } from 'react-icons/fi';
import { GrAppsRounded } from 'react-icons/gr';
import { FiAward } from 'react-icons/fi';
import { BiSupport } from 'react-icons/bi';
import { DiCss3 } from 'react-icons/di';
import { FaReact, FaBootstrap } from 'react-icons/fa';
import { SiTailwindcss, SiJavascript } from 'react-icons/si';
import { AiOutlineInstagram, AiOutlineGithub, AiFillFacebook, AiOutlineHome, AiOutlineUser, AiOutlineLaptop, AiOutlineSend, AiOutlineHtml5, AiOutlineFileDone } from "react-icons/ai";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [navApps, setNavApps] = useState(false);
    return (
        <>
            <Head>
                <title>Rrrrrrr.</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <main>
                <div className="bg-white pt-4 px-4">
                    <section className="text-slate-800">
                        <div className="text-slate-800 flex items-center justify-between ">
                            <h1 className="font-superMario text-2xl"><a href="#">RrrrrrrDev.</a></h1>
                            <GrAppsRounded className="text-3xl cursor-pointer" onClick={() => setNavApps(!navApps)} />
                        </div>
                        <nav className={!navApps ? "opacity-0 transition-all ease-in duration-300" : " bg-slate-200 px-3 py-3 rounded-md opacity-100 transition-all ease-in duration-300 my-4"}>
                            <ul className="flex justify-between items-center">
                                <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200">
                                    <AiOutlineHome className="text-2xl  cursor-pointer" />
                                    <a href="#">Home</a>
                                </li>
                                <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200">
                                    <AiOutlineUser className="text-2xl cursor-pointer" />
                                    <a href="#">About</a>
                                </li>
                                <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200">
                                    <AiOutlineLaptop className="text-2xl  cursor-pointer" />
                                    <a href="#">Works</a>
                                </li>
                                <li className="flex flex-col items-center px-2 py-2 rounded-md hover:bg-slate-400 transition-all ease-in-out duration-200">
                                    <AiOutlineSend className="text-2xl  cursor-pointer" />
                                    <a href="#">Contact</a>
                                </li>
                            </ul>
                        </nav>
                    </section>

                    <section className="flex items-center mb-5">
                        <div className="flex flex-col items-center gap-3">
                            <a href="#">
                                <AiOutlineInstagram className="text-black text-3xl" />
                            </a>
                            <span className="w-full bg-slate-800 h-[2px] border"></span>
                            <a href="#">
                                <AiOutlineGithub className="text-black text-3xl" />
                            </a>
                            <span className="w-full bg-slate-800 h-[2px] border"></span>
                            <a href="#">
                                <AiFillFacebook className="text-black text-3xl" />
                            </a>
                        </div>
                        <div className="overflow-hidden relative bg-gradient-to-b from-slate-400 rounded-full w-60 h-60 mx-auto md:h-96 md:w-96">
                            <Image src={me} objectFit="cover" className="grayscale" />
                        </div>
                    </section>
                    <div className="text-slate-700 pb-8">
                        <h1 className="text-4xl font-bold font-nulshock">Rifky Andriansyah</h1>
                        <h3 className="flex items-center font-semibold text-lg">
                            <span className="w-24 bg-slate-800 h-1 border mr-5 ml-1"></span> FrontEnd
                            Developer.
                        </h3>
                        <p className="text-slate-500 text-md font-[poppins] mb-3">
                            I'am FrontEnd Developer based in <span className="text-black font-serif font-semibold">Bandung</span> and i'am very
                            passionate and dedicated to my work.
                        </p>
                        <button className=" px-4 py-3 bg-slate-800 flex items-center text-white font-semibold rounded-[10px] font-[poppins]">Say Hello<FiSend className="ml-2 mt-[3px]" /></button>
                    </div>
                </div>
                <hr className="h-1 bg-slate-200" />
                <div className="pt-5 bg-white px-3">
                    <div>
                        <h1 className="text-slate-700 text-3xl text-center font-semibold">About Me</h1>
                        <h4 className="text-center text-slate-700">My Intoduction</h4>
                    </div>
                    <div className="overflow-hidden relative rounded-md w-60 h-60 mx-auto mb-4 md:h-96 md:w-96">
                        <Image src={aboutMe} objectFit="cover" className="grayscale" />
                    </div>
                    <div className="flex justify-evenly items-center">
                        <div className="bg-slate-800 flex flex-col justify-center items-center p-4 rounded-lg">
                            <FiAward className="text-slate-100 text-3xl" />
                            <h1 className="text-lg font-semibold">Experience</h1>
                            <p>1 Years</p>
                        </div>
                        <div className="bg-slate-800 flex flex-col justify-center items-center p-4 rounded-lg">
                            <AiOutlineFileDone className="text-slate-100 text-3xl" />
                            <h1 className="text-lg font-semibold">Completed</h1>
                            <p>5+ Project</p>
                        </div>
                        <div className="bg-slate-800 flex flex-col justify-center items-center p-4 rounded-lg">
                            <BiSupport className="text-slate-100 text-3xl" />
                            <h1 className="text-lg font-semibold">Support</h1>
                            <p>Online 24/7</p>
                        </div>

                    </div>
                    <h1 className="text-slate-700 font-semibold text-center mt-5 text-xl">What I Use?</h1>
                    <div className="py-2 flex gap-3 justify-evenly">
                        <div className="flex flex-col gap-2 justify-start py-2">
                            <h1 className="text-slate-700">Programming language</h1>
                            <div className="bg-slate-800 p-4 flex flex-col items-center rounded-lg">
                                <h1 className="font-semibold">HTML</h1>
                                <AiOutlineHtml5 className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center rounded-lg">
                                <h1 className="font-semibold">CSS</h1>
                                <DiCss3 className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center rounded-lg">
                                <h1 className="font-semibold">JAVASCRIPT</h1>
                                <SiJavascript className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                        </div>
                        <div className="flex flex-col gap-2 justify-start py-2">
                            <h1 className="text-slate-700">Library & Framework</h1>
                            <div className="bg-slate-800 p-4 flex flex-col items-center rounded-lg">
                                <h1 className="font-semibold">REACT</h1>
                                <FaReact className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center rounded-lg">
                                <h1 className="font-semibold">TAILWIND</h1>
                                <SiTailwindcss className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                            <div className="bg-slate-800 p-4 flex flex-col items-center rounded-lg">
                                <h1 className="font-semibold">BOOTSTRAP</h1>
                                <FaBootstrap className="text-2xl" />
                                <p className="text-sm">Medium</p>
                            </div>
                        </div>
                    </div>
                </div>
                <hr className="h-1 bg-slate-200" />
                <div>
                    <div className="bg-white">
                        <h1 className="text-slate-700 text-3xl text-center font-semibold">My Works</h1>
                        <h4 className="text-center text-slate-700">My Creation</h4>
                    </div>
                </div>
            </main>
        </>
    );
}
